# Generated by Django 5.0.6 on 2024-06-28 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_client_alter_accounts_user_reminder"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("Customers", "Customers"),
                            ("Vendors", "Vendors"),
                            ("Employees", "Employees"),
                        ],
                        default="Customers",
                        max_length=20,
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                (
                    "mobile_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("reminders", models.IntegerField(default=0)),
                ("user", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="CustomField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[("text", "Text"), ("numeric", "Numeric")],
                        max_length=10,
                    ),
                ),
                ("label", models.CharField(max_length=50)),
                ("value", models.CharField(max_length=100)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_fields",
                        to="accounts.contact",
                    ),
                ),
            ],
        ),
    ]
