# Generated by Django 5.0.6 on 2024-07-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_contact_customfield"),
    ]

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("template_name", models.CharField(max_length=100)),
                ("template_content", models.TextField()),
                ("user", models.CharField(max_length=100)),
            ],
        ),
    ]
