# Generated by Django 5.0.6 on 2024-07-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_template"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="group",
        ),
        migrations.AddField(
            model_name="contact",
            name="service_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
