# Generated by Django 4.2.9 on 2024-07-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_remove_contact_group_contact_service_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customfield",
            name="contact",
        ),
        migrations.RemoveField(
            model_name="client",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="reminder",
            name="notify_sms",
        ),
        migrations.AddField(
            model_name="client",
            name="contact_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="first_name",
            field=models.CharField(default="None", max_length=50),
        ),
        migrations.AddField(
            model_name="client",
            name="last_name",
            field=models.CharField(default="None", max_length=50),
        ),
        migrations.AddField(
            model_name="client",
            name="reminders",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="client",
            name="service_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="user",
            field=models.CharField(default="None", max_length=50),
        ),
        migrations.AlterField(
            model_name="client",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name="Contact",
        ),
        migrations.DeleteModel(
            name="CustomField",
        ),
    ]
