# Generated by Django 4.2.9 on 2024-07-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_remove_customfield_contact_remove_client_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="first_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="client",
            name="last_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="client",
            name="user",
            field=models.CharField(max_length=50),
        ),
    ]
