# Generated by Django 4.2.9 on 2024-07-04 17:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_alter_client_first_name_alter_client_last_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="template",
            name="user",
        ),
    ]
