# Generated by Django 4.2.9 on 2024-07-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_remove_template_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reminder",
            old_name="date",
            new_name="expiry_date",
        ),
        migrations.RenameField(
            model_name="reminder",
            old_name="time",
            new_name="reminder_time",
        ),
        migrations.RemoveField(
            model_name="reminder",
            name="client",
        ),
        migrations.RemoveField(
            model_name="reminder",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="reminder",
            name="notify_email",
        ),
        migrations.RemoveField(
            model_name="reminder",
            name="notify_push",
        ),
        migrations.RemoveField(
            model_name="reminder",
            name="repeat_interval",
        ),
        migrations.RemoveField(
            model_name="reminder",
            name="user",
        ),
        migrations.AddField(
            model_name="reminder",
            name="clients",
            field=models.ManyToManyField(to="accounts.client"),
        ),
        migrations.AddField(
            model_name="reminder",
            name="duration_after",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="reminder",
            name="duration_before",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="client",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="reminder",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
