# Generated by Django 4.2.9 on 2024-07-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_rename_date_reminder_expiry_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reminder",
            name="duration_after",
        ),
        migrations.RemoveField(
            model_name="reminder",
            name="duration_before",
        ),
        migrations.AddField(
            model_name="reminder",
            name="duration",
            field=models.IntegerField(default=0),
        ),
    ]
