# Generated by Django 4.2.9 on 2024-07-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_remove_reminder_duration_after_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reminder",
            name="duration",
            field=models.IntegerField(),
        ),
    ]
