# Generated by Django 4.2.9 on 2024-07-07 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_alter_reminder_duration"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[("text", "Text"), ("numeric", "Numeric")],
                        max_length=10,
                    ),
                ),
                ("label", models.CharField(max_length=50)),
                ("value", models.CharField(max_length=100)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_fields",
                        to="accounts.client",
                    ),
                ),
            ],
        ),
    ]
