# Generated by Django 4.2.9 on 2024-07-13 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_delete_customfield"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reminder",
            old_name="reminder_time",
            new_name="time",
        ),
        migrations.AddField(
            model_name="reminder",
            name="description",
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name="reminder",
            name="duration_type",
            field=models.CharField(
                choices=[("day", "Day"), ("week", "Week"), ("month", "Month")],
                default=None,
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="reminder",
            name="template",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.template",
            ),
        ),
    ]
