# Generated by Django 4.2.9 on 2024-07-13 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "accounts",
            "0015_remove_reminder_clients_remove_reminder_description_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reminder",
            name="client",
        ),
        migrations.AlterField(
            model_name="reminder",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="reminder",
            name="repeat_interval",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("custom", "Custom"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="reminder",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
