# Generated by Django 4.2.9 on 2024-07-13 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_remove_reminder_client_alter_reminder_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reminder",
            name="date",
        ),
        migrations.RemoveField(
            model_name="reminder",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="reminder",
            name="notify_email",
        ),
        migrations.RemoveField(
            model_name="reminder",
            name="notify_push",
        ),
        migrations.RemoveField(
            model_name="reminder",
            name="notify_sms",
        ),
        migrations.RemoveField(
            model_name="reminder",
            name="repeat_interval",
        ),
        migrations.RemoveField(
            model_name="reminder",
            name="user",
        ),
        migrations.AddField(
            model_name="reminder",
            name="clients",
            field=models.ManyToManyField(to="accounts.client"),
        ),
        migrations.AddField(
            model_name="reminder",
            name="description",
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name="reminder",
            name="duration",
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name="reminder",
            name="duration_type",
            field=models.CharField(
                choices=[("day", "Day"), ("week", "Week"), ("month", "Month")],
                default=None,
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="reminder",
            name="expiry_date",
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name="reminder",
            name="template",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.template",
            ),
        ),
        migrations.AlterField(
            model_name="reminder",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
