# Generated by Django 4.2.9 on 2024-07-20 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0019_remove_reminder_clients_remove_reminder_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reminder",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="reminder",
            name="notify_email",
        ),
        migrations.RemoveField(
            model_name="reminder",
            name="notify_push",
        ),
        migrations.RemoveField(
            model_name="reminder",
            name="notify_sms",
        ),
        migrations.RemoveField(
            model_name="reminder",
            name="repeat_interval",
        ),
        migrations.CreateModel(
            name="ReminderSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence_name", models.CharField(max_length=100)),
                ("sequence_date", models.DateField()),
                ("sequence_time", models.TimeField()),
                (
                    "reminder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sequences",
                        to="accounts.reminder",
                    ),
                ),
            ],
        ),
    ]
