# Generated by Django 4.2.9 on 2024-07-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0021_remove_reminder_client_remove_reminder_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remindersequence",
            name="reminder_time",
            field=models.TimeField(),
        ),
    ]
