# Generated by Django 4.2.9 on 2024-07-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0022_alter_remindersequence_reminder_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reminder",
            name="due_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="reminder",
            name="due_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="reminder",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="remindersequence",
            name="before_after",
            field=models.CharField(
                choices=[("before", "Before"), ("after", "After")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="remindersequence",
            name="duration_unit",
            field=models.CharField(
                choices=[("days", "Days"), ("weeks", "Weeks"), ("months", "Months")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="remindersequence",
            name="duration_value",
            field=models.PositiveIntegerField(),
        ),
    ]
