# Generated by Django 4.2.9 on 2024-07-20 15:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0023_alter_reminder_due_date_alter_reminder_due_time_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reminder",
            old_name="name",
            new_name="title",
        ),
    ]
