# Generated by Django 4.2.9 on 2024-07-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0024_rename_name_reminder_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="reminders",
            new_name="reminders_count",
        ),
        migrations.RemoveField(
            model_name="client",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="client",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="client",
            name="user",
        ),
        migrations.AlterField(
            model_name="client",
            name="contact_number",
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="name",
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name="client",
            name="service_type",
            field=models.CharField(default=None, max_length=100),
        ),
    ]
