# Generated by Django 4.2.9 on 2024-07-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0025_rename_reminders_client_reminders_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="contact_number",
            field=models.CharField(max_length=15),
        ),
    ]
