# Generated by Django 4.2.9 on 2024-07-20 16:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0026_alter_client_contact_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="reminders_count",
        ),
    ]
