# Generated by Django 4.2.9 on 2024-07-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0028_alter_reminder_due_date_alter_reminder_due_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reminder",
            name="due_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="reminder",
            name="due_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="remindersequence",
            name="reminder_time",
            field=models.TimeField(),
        ),
    ]
