# Generated by Django 4.2.9 on 2024-07-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0029_alter_reminder_due_date_alter_reminder_due_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="template",
            name="template_content",
        ),
        migrations.RemoveField(
            model_name="template",
            name="template_name",
        ),
        migrations.AddField(
            model_name="template",
            name="matter",
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name="template",
            name="name",
            field=models.CharField(default=None, max_length=255),
        ),
    ]
