# Generated by Django 4.2.9 on 2024-07-22 12:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0030_remove_template_template_content_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="template",
            old_name="matter",
            new_name="content",
        ),
    ]
