# Generated by Django 4.2.9 on 2024-07-22 12:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0031_rename_matter_template_content"),
    ]

    operations = [
        migrations.RenameField(
            model_name="template",
            old_name="name",
            new_name="title",
        ),
    ]
